services:
  apiserver:
    image: asabhi6776/mod-watcher:latest
    container_name: mod-watcher-apiserver
    ports:
      - "5005:5000"
    volumes:
      - ./monitored_mods.json:/app/monitored_mods.json:rw
    entrypoint: ["python", "app.py"]
    restart: unless-stopped
  watcher:
    image: asabhi6776/mod-watcher:latest
    container_name: mod-watcher-watcher
    depends_on:
      - apiserver
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./monitored_mods.json:/app/monitored_mods.json:rw
    command: python watcher.py
  swagger:
    image: swaggerapi/swagger-ui
    container_name: mod-watcher-swagger
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/swagger.yaml
    volumes:
      - ./swagger.yaml:/app/swagger.yaml:ro
    restart: unless-stopped